### ISSUE TITLE
Add fonts to the Google Web Fonts

### ISSUE THREAD

**Issue by mociepka** [christiannaths/redacted-font#1]
Can you add your fonts to the Google Web Fonts? This will significantly simplify the web developers work.

http://www.google.com/webfonts/#AboutPlace:about

**Comment by macleodsawyer** [comment]
+1

**Comment by Turqueso** [comment]
:+1:

**Comment by xantilon** [comment]
:+1:

**Comment by battaglr** [comment]
:+1:

**Comment by davelab6** [comment]
Maybe I can help as there is so much interest in this :D

**Comment by christiannaths** [comment]
I clearly need some help. Haha. Give me the weekend to ignore all other manner of life events and work requirements and see if I can't at least get the ball rolling and I'll see where I'm at with it. If I can define where I need help I'll post it here and gratefully accept any help you (or anyone else) can offer.

I'm blown away by how well this thing has been received from the start, and really stoked to see that there (for some unknown reason) has been a recent resurgence of really encouraging interest in it. Gives me a ton of needed motivation. Thanks everyone :)

**Comment by christiannaths** [comment]
Just wanted to leave an update on this. I bunkered down this weekend and spent some time familiarizing myself with FontForge. There is a new source in `src/` for FF. I managed to get Redacted Regular created (not that it's a particularly difficult task, it being a single glyph reused 315 times, :P)

I also installed the fontbakery project (https://github.com/googlefonts/fontbakery) on Travis CI, so later today I'll try pushing a UFO format of the new version and see if I can't get that working. The build seems to be completing but it's not publishing much to the `gh-pages` branch as promised. Maybe @davelab6 can provide some insight as to why this would be the case?

I feel like I'm in a pretty good position now to finish the rebuild by the end of the week. So hopefully I'll have the full gamut of Redacted rebuilt and ready to be submitted again to Google. Thanks for your patience everyone.

**Comment by benjick** [comment]
Any news on this?

**Comment by flexbox** [comment]
Hello @christiannaths 
Your project is awesome and i have build a small thing with it 
http://flexbox.github.io/foundation-boilerplate/templates/homepage.html

Let me know if you are looking for some feedback

**Comment by howardroark** [comment]
:+1: This would remove any need for me to fiddle with a way to get these files into a build process.

**Comment by davelab6** [comment]
Sorry guys, this is in my queue but behind some non-latin fonts I'm working
on :)

**Comment by Turqueso** [comment]
any news?

**Comment by christiannaths** [comment]
This repo is in serious need of some TLC. If anyone wants to pitch in, I'd more than welcome the help.

**Comment by robszumski** [comment]
A few years late here but would love to see this as a Google Font. Great work on the project.

**Comment by jessycormier** [comment]
Just came across this font as well looking for alternatives to "blokk" which is missing. Was thinking of setting up a new font of my own but this one seems visually fantastic. I have some experience in web dev and those kinds of technologies so I can lend a hand in setting up those things. I've even dabbled in making font icons using online utilities, and used vector applications before.

I think giving this font a 2020 refresh so it can be included in things like Google's Fonts and Adobe (thinking of the XD application) would be fantastic to give a visual impression.

Are you still around @christiannaths ?

**Comment by christiannaths** [comment]
Hey @jessycormier. Yeah, I had some spare time about 3 months ago and was _finally_ set to put this back on my radar, then I got a new contract and got slammed with work again. I'd really appreciate the help! I think it needs a complete refresh as well. I'd love to hear your ideas. Let me know if you want to do a call sometime to meet and discuss.

**Comment by jessycormier** [comment]
Taking a look at some of these fonts, perhaps we can find out how they built their tooling and fonts and base it off it.

* https://github.com/sharanda/manrope
* https://github.com/RedHatOfficial/Overpass
* https://github.com/larsenwork/Gidole

I stubbled across a few open source font creation tools as well. https://fontforge.org/ stood out to me.

@christiannaths I've sent you an email if we wanted to chat offline may be quicker to get some details.

**Comment by christiannaths** [comment]
Closed with https://github.com/google/fonts/pull/4004 🎉

**Comment by benjick** [comment]
The wait is finally over! 😍😍

https://fonts.google.com/specimen/Redacted

https://fonts.google.com/specimen/Redacted+Script

**Comment by jessycormier** [comment]
Amazing work! Thank you so much.

**Comment by mociepka** [comment]
OMG, that was a journey. I forgot what was the purpose :D
