### ISSUE TITLE
Font Validation Mac OSX 10.7.5

### ISSUE THREAD

**Issue by EricWOdom** [christiannaths/redacted-font#10]
![Screen Shot 2013-03-05 at 10 36 31 AM](https://f.cloud.github.com/assets/2027376/222099/db93303a-85b2-11e2-907a-f2acab5bc1d1.png)

I'm getting 3 'serious errors' when attempting to install redacted on OSX 10.7.5. Granted, the computer I'm on is a managed computer at work, so that could be the issue, but I have successfully other fonts on this system before, so not sure.

Installed on my MacBook running 10.8.2 with no issues, but 10.7.5 does not like this at all. Any help would be great.

**Comment by christiannaths** [comment]
With the recent publication to Google Fonts, I'm going to close this as fixed. Download are now available here, and should work on all platforms:

- https://fonts.google.com/specimen/Redacted
- https://fonts.google.com/specimen/Redacted+Script
