### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by oste** [christiannaths/Redacted-Font#14]
Hey, I recently started using Bower to manage some front end dependencies. It looks like Redacted-Font is not available via Bower. Here is a list of available components http://sindresorhus.com/bower-components. Thoughts on submitting this? More info here http://bower.io

Thanks - love this font for mocks!

**Comment by howardroark** [comment]
Hey @christiannaths ... Could you tag a release on GitHub instead maybe?  That way I can target the archive GitHub offers up with my build scripts.  I can do it from master as well, but with a tagged release I can match the file against an md5 sum and not worry about it changing.

**Comment by codeyash** [comment]
bower install Redacted-Font

I've added package. Install it.

@Author if you want me to remove so that you can add let me know.

-Yash

**Comment by equinusocio** [comment]
Bower is now at the end of his life. Will close soon.
