### ISSUE TITLE
Downloading the latest builds

### ISSUE THREAD

**Issue by thomasklemm** [christiannaths/Redacted-Font#20]
Nice work on the font, @christiannaths!

What's the best way to download the font? Could you maybe add a download link for the desktop and webfont files in the Readme?

Thanks!

Best, Thomas

**Comment by christiannaths** [comment]
Hmm, I guess I assume most people are familiar with Github, so I definitely glossed over that part. For now though:

![screen shot 2015-03-09 at 4 39 38 pm](https://cloud.githubusercontent.com/assets/11584/6566065/4f5b59ce-c67b-11e4-8921-0c2ed3d0e569.png)

**Comment by christiannaths** [comment]
I just realized that since the current build is broken (wip) that the compiled font files are not showing up. The best I can offer is to download from the branch "old-sources". I added a direct link in the readme

**Comment by thomasklemm** [comment]
Thanks for taking a look, thought I must have missed something since I only found the regular font, but not the script ones.
