### ISSUE TITLE
Embedding the font within an EPUB (licensing and obfuscating)

### ISSUE THREAD

**Issue by GizMecano** [christiannaths/Redacted-Font#29]
I am currently working on an EPUB project in which will be embed your font. As it is stated by the OFL license, I will add a copyright notice, but I currently wonder [what is the proper way to include the license file](http://opensource.stackexchange.com/q/2844/5047) itself. Maybe you could have some answer?

On the other hand, I would want to know if you recommend to use [an obfuscation method](http://www.idpf.org/epub/30/spec/epub30-ocf.html#font-obfuscation) when your font is embedded in such a file.

**Comment by christiannaths** [comment]
No obfuscation necessary, since the font is free to distribute. For including the license, I like the top answer at the link you provided.

**Comment by GizMecano** [comment]
Thanks for your answer. 
I have opted for [this method](http://opensource.stackexchange.com/a/2859/5047) which grants an easy access to the license text. 
Note that I have found [another manner](http://ebooks.stackexchange.com/a/6486/6569), but it seems invalid according to my working environment.
