### ISSUE TITLE
Add proper releases

### ISSUE THREAD

**Issue by bmaupin** [christiannaths/redacted-font#34]
As best as I can tell, the only way to download this font is through the link in the readme:
https://github.com/christiannaths/Redacted-Font/archive/old-sources.zip

... which appears to be an archive of the `old-sources` branch.

It would be nice if this font was versioned and released using GitHub releases: https://help.github.com/en/articles/about-releases

Edit: my error had nothing to do with the font being invalid; apparently it's also the error Windows gives if you don't have permission to install a font. But it'd still be great to have proper releases :)

~~In particular I'm asking because I'm getting an error trying to install this font in Windows Server 2016:
![redacted-font-bug](https://user-images.githubusercontent.com/346123/65057671-f1d65280-d940-11e9-8bd4-5d5a5e462fa4.png)~~

~~It's possible that I'm running into #5, which was fixed on 2013-03-05. If I'm correct about the current download link, then the fonts are dated 2013-03-02:
https://github.com/christiannaths/Redacted-Font/tree/old-sources/fonts~~

~~But without knowing which version I'm using and which version that bug was fixed, I'm not sure if I'm running into a new bug or #5.~~

Thanks!

**Comment by christiannaths** [comment]
With the recent publication to Google Fonts, I'm going to close this. Download are now available here, and should work on all platforms:

- https://fonts.google.com/specimen/Redacted
- https://fonts.google.com/specimen/Redacted+Script
