### ISSUE TITLE
Font not legible 

### ISSUE THREAD

**Issue by AskAlice** [christiannaths/Redacted-Font#4]
It is hard to make out the words and letters on this font. It looks pretty nice, but please fix.

**Comment by kkm000** [comment]
@AskAlice, love it! I just discovered the font at Google's, came here to open the same issue, and realized I was 9 years too late, and it had been a wontfix! By now, it's no longer a bug, it's a feature...

@christiannaths, it's the Best. Font. Ever. to cheese the mates who leave their computers unlocked!!!
